### ISSUE TITLE
Instance of 'UnsupportedUserLocation'

### ISSUE THREAD

**Issue by Sofitt** [peaashmeter/schizodem#1]
{property: Анализ, value: 0.8, response: Instance of 'UnsupportedUserLocation'}
{property: Наибольшее число показателей, reference: 0.5, evaluation: Instance of 'UnsupportedUserLocation'}

**Comment by peaashmeter** [comment]
Seems like Google did something wrong to the location restrictions for today. I have already notified them. Hope it gets fixed soon.

**Comment by peaashmeter** [comment]
Если что, оно работает из Казахстана и судя по справке, нет ничего, что помешало бы его работе...

**Comment by peaashmeter** [comment]
В качестве временного решения я добавил предостерегающий заголовок, и, опять же, написал в гугл.
